FROM python:3.13-alpine3.21

WORKDIR /app

RUN pip install --no-cache-dir grpcio grpcio-tools "fastapi[standard]"

COPY ./task_manager.proto .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. task_manager.proto

COPY ./cliente.py .

CMD ["fastapi", "run", "cliente.py", "--host", "0.0.0.0", "--port", "8000"]