# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_manager.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'task_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_manager.proto\x12\x0ctask_manager\"\x1e\n\x0b\x43onnRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tConnReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"F\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"3\n\rCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bListRequest\"1\n\x0cListResponse\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.task_manager.Task\"O\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf9\x02\n\x0bTaskManager\x12\x39\n\x06\x43reate\x12\x1b.task_manager.CreateRequest\x1a\x12.task_manager.Task\x12\x33\n\x03Get\x12\x18.task_manager.GetRequest\x1a\x12.task_manager.Task\x12=\n\x04List\x12\x19.task_manager.ListRequest\x1a\x1a.task_manager.ListResponse\x12\x39\n\x06Update\x12\x1b.task_manager.UpdateRequest\x1a\x12.task_manager.Task\x12:\n\x06\x44\x65lete\x12\x1b.task_manager.DeleteRequest\x1a\x13.task_manager.Empty\x12\x44\n\x0e\x43onnectionTest\x12\x19.task_manager.ConnRequest\x1a\x17.task_manager.ConnReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNREQUEST']._serialized_start=36
  _globals['_CONNREQUEST']._serialized_end=66
  _globals['_CONNREPLY']._serialized_start=68
  _globals['_CONNREPLY']._serialized_end=96
  _globals['_TASK']._serialized_start=98
  _globals['_TASK']._serialized_end=168
  _globals['_CREATEREQUEST']._serialized_start=170
  _globals['_CREATEREQUEST']._serialized_end=221
  _globals['_GETREQUEST']._serialized_start=223
  _globals['_GETREQUEST']._serialized_end=247
  _globals['_LISTREQUEST']._serialized_start=249
  _globals['_LISTREQUEST']._serialized_end=262
  _globals['_LISTRESPONSE']._serialized_start=264
  _globals['_LISTRESPONSE']._serialized_end=313
  _globals['_UPDATEREQUEST']._serialized_start=315
  _globals['_UPDATEREQUEST']._serialized_end=394
  _globals['_DELETEREQUEST']._serialized_start=396
  _globals['_DELETEREQUEST']._serialized_end=423
  _globals['_EMPTY']._serialized_start=425
  _globals['_EMPTY']._serialized_end=432
  _globals['_TASKMANAGER']._serialized_start=435
  _globals['_TASKMANAGER']._serialized_end=812
# @@protoc_insertion_point(module_scope)
